[build-system]
requires = ["setuptools>=77", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "fal-demo-wan-lora-trainer"
version = "0.0.1"
description = "Deploy Wan LoRA training on fal"
requires-python = ">=3.11"
dependencies = [
    "fal",
    "pydantic",
    "accelerate==1.4.0",
    "av==14.2.0",
    "bitsandbytes==0.45.3",
    "datasets==3.3.2",
    "deepspeed==0.14.5",
    "diffusers==0.32.2",
    "easydict==1.13",
    "einops==0.8.1",
    "ftfy==6.3.1",
    "flash-attn @ https://github.com/Dao-AILab/flash-attention/releases/download/v2.7.4.post1/flash_attn-2.7.4.post1+cu12torch2.6cxx11abiFALSE-cp311-cp311-linux_x86_64.whl",
    "imageio==2.37.0",
    "imageio-ffmpeg==0.6.0",
    "omegaconf==2.3.0",
    "peft==0.14.0",
    "pillow==10.4.0",
    "protobuf==6.31.1",
    "psutil==7.0.0",
    "safetensors==0.5.3",
    "sentencepiece==0.2.0",
    "tensorboard==2.19.0",
    "termcolor==2.5.0",
    "toml==0.10.2",
    "torch==2.6.0",
    "torch-optimi==0.2.1",
    "torchvision==0.21.0",
    "tqdm==4.67.1",
    "transformers==4.49.0",
    "triton==3.2.0",
    "wandb",
]

[tool.setuptools.packages.find]
include = ["fal_demo_wan_lora_trainer*"]

[tool.fal.apps.wan-lora-trainer]
python_entry_point = "fal_demo_wan_lora_trainer.app:WanLoRATrainerDemo"
auth = "private"
requirements = ["."]
python_version = "3.11"
machine_type = "GPU-H100"
num_gpus = 1
keep_alive = 0
request_timeout = 43200

[tool.fal.apps.wan-lora-trainer._scheduler_options]
region = ["us-central", "us-west", "us-east", "eu-north"]
